# -*- coding: utf-8 -*-
"""Data processing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JeR5QOQey0QgQcl1QgpNrayBkysE3RPG
"""

import re
import pandas as pd
import json

#load data here (jdihn)
path = '/content/drive/MyDrive/train.01.jsonl'

df = pd.read_json(path, lines=True)
columns = ['category', 'gold_labels', 'id', 'source', 'source_url']
df = df.drop(columns, axis=1)
df.head()

with pd.option_context('display.max_colwidth', None):
  print(df.head(1))

def conv_to_str(list):
  str = " "
  return (str.join(list))
def conv_to_par(line):
  str = "\n"
  return (str.join(line))

def process_par(par):
  y = ""
  for i in par:
    x = [conv_to_str(lines) for lines in i]
    z = '\n'.join(x)
    y+=z
  return y

def process_sum(json):
  list_line = [conv_to_str(lines) for lines in json]
  list_final = '\n'.join(list_line)
  return list_final

sum = []
for summary in df['summary']:
  sum.append(summary)


par = []
for paragraphs in df['paragraphs']:
  par.append(paragraphs)

print(sum[0])

sum_clean = [process_sum(i) for i in sum ]
par_clean = [process_par(i) for i in par]

dict = {'paragraphs':par_clean, 'summary':sum_clean}
data = pd.DataFrame(dict)

data.head()
# data.shape[0]

#save processed data
# data.to_csv(r'/content/indosum.csv', index=False, header=True)

#if you want to upload to drive
# from google.colab import drive
# drive.mount('drive')
# !cp indosum.csv "drive/My Drive/"